name: Label PRs to test branch

on:
  pull_request:
    # branches:
    #   - test-add-label

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add 'test' label to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(jq -r '.pull_request.number' < "$GITHUB_EVENT_PATH")
          gh pr edit "$pr_number" --add-label "test"
          echo "Label 'test' added to PR #$pr_number"

      - name: Share a fun fact
        run: |
          echo " Did you know? The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes!"